package storage

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/harishnagaraju/astramind/internal/infrastructure/models"
)

func ExportMarkdown(
	session string,
	messages []models.Message,
) error {

	file := fmt.Sprintf(
		"exports/%s.md",
		session,
	)

	err := os.MkdirAll(filepath.Dir(file), 0755)
	if err != nil {
		return err
	}

	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer f.Close()

	userCount := 0
	assistantCount := 0

	for _, msg := range messages {
		switch msg.Role {
		case "user":
			userCount++
		case "assistant":
			assistantCount++
		}
	}

	_, err = fmt.Fprintf(
		f,
		`# AstraMind Conversation Export

---

## Session Information

| Item | Value |
|------|-------|
| Session | %s |
| Exported | %s |
| User Messages | %d |
| Assistant Messages | %d |
| Total Entries | %d |

---

`,
		session,
		time.Now().Format("2006-01-02 15:04:05"),
		userCount,
		assistantCount,
		len(messages),
	)

	if err != nil {
		return err
	}

	for i, msg := range messages {

		role := strings.ToUpper(msg.Role)

		_, err = fmt.Fprintf(
			f,
			`## Message %d

### %s

%s

---

`,
			i+1,
			role,
			msg.Content,
		)

		if err != nil {
			return err
		}
	}

	_, err = fmt.Fprintf(
		f,
		`
Generated by **AstraMind**

https://github.com/harishnagaraju/astramind
`,
	)

	return err
}
