@echo off
setlocal enabledelayedexpansion

rem Usage:
rem   scripts\regression.bat          - fast, no web server involved
rem   scripts\regression.bat --web    - also runs the web UI smoke test
rem
rem Log capture: this script calls FIVE other scripts (build.bat,
rem test.bat, coverage.bat, check_knowledge_base.bat,
rem check_rag_behavior.bat), and most of what needs saving - the full
rem `go test` output, coverage numbers - is generated by those calls,
rem not by static echo lines in this file. The line-by-line
rem screen+file duplication used in check_rag_behavior.bat cannot
rem work here, since that output doesn't exist as text in this script
rem to duplicate. Capturing an entire multi-process run like this
rem needs a real tee - batch has none natively, so this relaunches
rem itself once through PowerShell's Tee-Object (ships with Windows
rem 10/11 by default), which correctly captures everything printed by
rem this script AND every script it calls.
rem
rem Status reporting: each step's real exit code is captured into its
rem own status variable (PASS/FAIL/SKIPPED), and the summary reports
rem what actually happened - not a hardcoded "PASS" printed
rem unconditionally regardless of outcome, which is what an earlier
rem version did. enabledelayedexpansion (!VAR! syntax) is required
rem here specifically because status is set and then read again
rem within the same parenthesized if-block - %VAR% alone would only
rem ever show the value from before the block started.
if "%~1"=="_LOGGING_" goto :run_logged

for /f "delims=" %%T in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') do set TIMESTAMP=%%T
set REGLOG=regression_win_%TIMESTAMP%.log

powershell -NoProfile -Command "& { & '%~f0' _LOGGING_ %* 2>&1 | Tee-Object -FilePath '%REGLOG%' }"
exit /b %errorlevel%

:run_logged
shift

set RUN_WEB=
if "%~1"=="--web" set RUN_WEB=--web

set BUILD_STATUS=SKIPPED
set TEST_STATUS=SKIPPED
set COVERAGE_STATUS=SKIPPED
set KBRAG_STATUS=SKIPPED

echo ====================================
echo  AstraMind Regression Test Suite
echo ====================================
echo.

echo [1/4] Build...
call scripts\build.bat
if !errorlevel! equ 0 (set BUILD_STATUS=PASS) else (set BUILD_STATUS=FAIL)

if "!BUILD_STATUS!"=="PASS" (
    echo.
    echo [2/4] Tests...
    call scripts\test.bat
    if !errorlevel! equ 0 (set TEST_STATUS=PASS) else (set TEST_STATUS=FAIL)
)

if "!TEST_STATUS!"=="PASS" (
    echo.
    echo [3/4] Coverage...
    call scripts\coverage.bat
    if !errorlevel! equ 0 (set COVERAGE_STATUS=PASS) else (set COVERAGE_STATUS=FAIL)
)

if "!COVERAGE_STATUS!"=="PASS" (
    echo.
    echo [4/4] Knowledge Base ^& RAG Regression...
    call scripts\check_knowledge_base.bat
    set KB_ERR=!errorlevel!
    call scripts\check_rag_behavior.bat %RUN_WEB%
    set RAG_ERR=!errorlevel!
    if !KB_ERR! equ 0 if !RAG_ERR! equ 0 (
        set KBRAG_STATUS=PASS
    ) else (
        set KBRAG_STATUS=FAIL
    )
)

echo.
echo ====================================
echo  Regression Summary
echo ====================================
echo Build      : !BUILD_STATUS!
echo Tests      : !TEST_STATUS!
echo Coverage   : !COVERAGE_STATUS!
echo KB ^& RAG   : !KBRAG_STATUS!
echo ====================================

if "!BUILD_STATUS!"=="PASS" if "!TEST_STATUS!"=="PASS" if "!COVERAGE_STATUS!"=="PASS" if "!KBRAG_STATUS!"=="PASS" (
    echo  AstraMind is READY
    echo ====================================
    exit /b 0
) else (
    echo  AstraMind is NOT READY - see above
    echo ====================================
    exit /b 1
)