# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - feature/**
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
   
    - name: Format
      run: go fmt ./...

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Generate Coverage
      run: |
        mkdir -p tests/coverage
        go test -coverprofile=tests/coverage/coverage.out ./...
        go tool cover -func=tests/coverage/coverage.out > tests/coverage/coverage.txt
        go tool cover -html=tests/coverage/coverage.out -o tests/coverage/coverage.html
